apiVersion: 1

groups:
  - name: kubernetes-alerts
    orgId: 1
    folder: alerts
    interval: 1m
    rules:
      - uid: high-cpu-alert
        title: High CPU Usage
        condition: B
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            model:
              expr: 'avg(1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100'
              instant: false
              range: true
              refId: A
            datasourceUid: '${PROMETHEUS_DATASOURCE_UID}'
          - refId: B
            queryType: ''
            model:
              conditions:
                - evaluator:
                    params: [80]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              type: classic_conditions
            datasourceUid: __expr__
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: 'CPU usage is above 80% for more than 5 minutes'
          summary: 'High CPU usage detected on Kubernetes cluster'
        labels:
          severity: warning
          team: devops

      - uid: high-memory-alert
        title: High Memory Usage
        condition: B
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            model:
              expr: '(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100'
              instant: false
              range: true
              refId: A
            datasourceUid: '${PROMETHEUS_DATASOURCE_UID}'
          - refId: B
            queryType: ''
            model:
              conditions:
                - evaluator:
                    params: [85]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              type: classic_conditions
            datasourceUid: __expr__
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: 'Memory usage is above 85% for more than 5 minutes'
          summary: 'High memory usage detected on Kubernetes cluster'
        labels:
          severity: warning
          team: devops

