apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-alerts
    receivers:
      - uid: email-alerts-uid
        type: email
        settings:
          addresses: ${SMTP_USER}
          subject: "Grafana Alert: {{ .GroupLabels.alertname }}"
          message: |
            {{ range .Alerts }}
            Alert: {{ .Annotations.summary }}
            Description: {{ .Annotations.description }}
            Status: {{ .Status }}
            Time: {{ .StartsAt }}
            {{ end }}

policies:
  - orgId: 1
    receiver: email-alerts
    group_by: ['alertname']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    routes: []