# not used (standard is used now)
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent-nodeport
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: jenkins-controller
spec:
  type: NodePort
  ports:
  - port: 50000
    targetPort: 50000
    nodePort: 32001
    name: agent-listener
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: jenkins-controller