apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Use Minikube's default storage class
  resources:
    requests:
      storage: 2Gi  # Minimal size - will match available PV