# Absolute minimal Jenkins configuration
controller:
  admin:
    existingSecret: "jenkins-admin-secret"
    userKey: "username"
    passwordKey: "password"
  
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  
  persistence:
    enabled: true
    existingClaim: "jenkins-pvc"
  
  serviceType: NodePort
  nodePort: 32000
  
  serviceAccount:
    create: true
  
  # Install Kubernetes plugin for agents
  installPlugins:
    - kubernetes:4203.v1dd44f5b_1cf9
    - configuration-as-code:1971.vf9280461ea_89
  
  # Master has executors but agents preferred
  numExecutors: 2

# Enable agents for distributed builds
agent:
  enabled: true
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"