# Simplified Jenkins values for basic installation
controller:
  admin:
    # Credentials will be provided via Kubernetes Secret
    existingSecret: "jenkins-admin-secret"
    userKey: "username"
    passwordKey: "password"
  
  # Minimal resources
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  
  # Use existing PVC
  persistence:
    enabled: true
    existingClaim: "jenkins-pvc"
  
  # Service configuration
  serviceType: NodePort
  nodePort: 32000
  
  # ServiceAccount
  serviceAccount:
    create: true

# Disable agent for minimal setup
agent:
  enabled: false