service:
  type: NodePort
  nodePorts:
    grafana: 30030

persistence:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

admin:
  existingSecret: grafana-admin-secret
  userKey: username
  passwordKey: password

config:
  useGrafanaIniFile: true
  grafanaIniConfigMap: grafana-config

datasources:
  secretName: grafana-datasources