apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-minikube
spec:
  capacity:
    storage: 2Gi  # Minimal size for local testing
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-storage
  hostPath:
    path: /tmp/jenkins-data  # Minikube local path