apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-storage
  namespace: jenkins
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-storage
  hostPath:
    path: /mnt/data/jenkins-data  # Minikube's persistent mount (or `/tmp/jenkins-data` custom path)
